### PR TITLE
add requests to requirements

### PR DESCRIPTION
**Pull request by gotenksIN**

### CODE REVIEW

**Comment by skittles9823** [comment]
@songotenks69 Requests aren't used in Kang tho

**Comment by yash-garg** [comment]
@songotenks69 What's the need sur?

**Comment by gotenksIN** [comment]
@skittles9823 then why is it there in kang.py ;-;

**Comment by skittles9823** [comment]
@songotenks69 It's not 👀👀

**Comment by nitanmarcel** [comment]
@songotenks69 it's not there. The modules uses urllib for making requests

**Comment by skittles9823** [comment]
@nitanmarcel It's probs a remnant from the stickers.py module.

**Comment by gotenksIN** [comment]
Ik
But it imports it and caused heroku to crash

**Comment by SphericalKat** [comment]
@songotenks69 Pruu

**Comment by gotenksIN** [comment]
Chup

**Pull request closed without merging**
